// Code generated by FTL. DO NOT EDIT.
package console

import (
	"context"
	ftlbuiltin "ftl/builtin"
	lib "github.com/block/ftl/backend/console/testdata/go"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
)

type GetClient func(context.Context, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, External]) (ftlbuiltin.HttpResponse[Response, string], error)

type VerbClient func(context.Context, External) (External, error)

func init() {
	reflection.Register(
		reflection.ExternalType(*new(lib.External)),

		reflection.ProvideResourcesForVerb(
			Get,
		),

		reflection.ProvideResourcesForVerb(
			Verb,
		),
	)
}
