// Code generated by FTL. DO NOT EDIT.
package db

import (
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
	"github.com/block/ftl/go-runtime/server"
)

//ftl:database postgres testdb
type TestdbConfig struct{}

type TestdbHandle = ftl.DatabaseHandle[TestdbConfig]

func init() {
	reflection.Register(
		reflection.Database[TestdbConfig]("testdb", server.InitPostgres),
	)
}
