apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-schemaservice
  {{- if .Values.schemaservice.service.annotations }}
  annotations:
    {{- toYaml .Values.schemaservice.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range .Values.schemaservice.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .appProtocol }}
      appProtocol: {{ .appProtocol }}
      {{- end }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "ftl-schema.selectorLabels" . | nindent 4 }}
  type: {{ .Values.schemaservice.service.type | default "ClusterIP" }}
