apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-schema
  {{- if .Values.schema.services.schema.annotations }}
  annotations:
    {{- toYaml .Values.schema.services.schema.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.schema.services.schema.port }}
      protocol: TCP
  selector:
    {{- include "ftl-schema.selectorLabels" . | nindent 4 }}
  type: {{ .Values.schema.services.schema.type | default "ClusterIP" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-schema-raft
  {{- if .Values.schema.services.raft.annotations }}
  annotations:
    {{- toYaml .Values.schema.services.raft.annotations | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - name: raft
      port: {{ .Values.schema.services.raft.port }}
      protocol: TCP
  selector:
    {{- include "ftl-schema.selectorLabels" . | nindent 4 }}
  type: {{ .Values.schema.services.raft.type | default "ClusterIP" }}