services:
  localstack:
    image: localstack/localstack@sha256:3ea49f17af1f4f89f85ab1d366865d126829bb548e87bc044dbff3d02424f459
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
