services:
  localstack:
    image: localstack/localstack@sha256:f83f4f59f9ed2131c993d1ffbc8f0d8d87fae45020a3620bd6a253ba7331a4ae
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
