services:
  localstack:
    image: localstack/localstack@sha256:1640649a21e7e1d8b8541791e916a65f8eff782a587d55a929b45ba0d50e99f4
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
