services:
  localstack:
    image: localstack/localstack@sha256:0cffde4f179651dacb058f3ec8209c6abae251366a749fd82822d53ef0605470
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
