services:
  localstack:
    image: localstack/localstack@sha256:df334a50aa7ae978fa962022c3a7276febea6c91d943d87ea16d10b1c3ba50bd
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
