FROM ubuntu:24.04@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782 AS builder
RUN apt-get update
RUN apt-get install -y curl git zip

# Seed some of the most common tools - this will be cached
COPY ./bin /src/bin
ENV PATH="/src/bin:$PATH"
ENV HERMIT_STATE_DIR=/hermit
RUN hermit install openjdk-21.0.3_9
RUN mvn -B --version

# Finally create the runtime image.
FROM ftl0/ftl-runner:latest

WORKDIR /root/

ENV PATH="/root/jdk/bin:$PATH"
ENV JAVA_HOME="/root/jdk"
COPY --from=builder /hermit/pkg/openjdk-21.0.3_9/ /root/jdk/
