services:
  localstack:
    image: localstack/localstack@sha256:301cacb998eb1a73546d47779e2f348f2c61702f6f52a726993c62234daf4018
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
