services:
  localstack:
    image: localstack/localstack@sha256:3d1cb976135ac9915a9052cad659da1e813a7f47d7609fe9cc77eb00e219a809
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
