services:
  localstack:
    image: localstack/localstack@sha256:a3cd723aa8e3e94b96e5a288c79d48fe59f6fe2fca7e64d26a4a69c742177994
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
