services:
  localstack:
    image: localstack/localstack@sha256:52517ecee40f7128209980b3ce8a00f7758b9371777296858ea9b237493300d1
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
