services:
  localstack:
    image: localstack/localstack@sha256:f0512bc9f876d09bbe6754c8f72fa7a8b7713804267707930594ce1cd08f804f
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
