services:
  localstack:
    image: localstack/localstack@sha256:7e3fc8d665454679098f60bc2f4ee26837d5f62cb6b5b6ada66b8327641fa863
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
