services:
  localstack:
    image: localstack/localstack@sha256:099992fc62f21f3f07f0da107e828b86fda611f79e9586b452d0def943c66b57
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
