services:
  localstack:
    image: localstack/localstack@sha256:3d59731cbd48b6f7b78e82c61951f33cf8f743deaa72f284fd09919e033dae3e
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
