services:
  localstack:
    image: localstack/localstack@sha256:7a53fb3f0902367431c47deb5d2238a9f1bc0717d2f52bca25c6c4c729062a8e
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
