services:
  localstack:
    image: localstack/localstack@sha256:19bf316d1736687ed5950681d5fbb601a23caf73ad4b2afb89160d02c55977f7
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
