services:
  localstack:
    image: localstack/localstack@sha256:a5bdfc88b9f81819be5c7cf838a06a7f094826afa28accd79cab71ee4daef7d6
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
