services:
  localstack:
    image: localstack/localstack@sha256:04bdd250aa25563897f4ba20b6f83e48fcc392070c093515990abfad645a5b81
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
