services:
  localstack:
    image: localstack/localstack@sha256:64205c9cc7b885570edfbdb0a97e5ba0802ab5fbeb4efdacf2ddf1206c1cde36
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
