services:
  localstack:
    image: localstack/localstack@sha256:2b0721c9cb01916c7e2cd905b7951fe744b10c1faa35715f47936ddcaabdd822
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
