services:
  localstack:
    image: localstack/localstack@sha256:302b72952bb8bf9fb1e7661b0fab532e0db270b0d5e563607a90b207f314f42d
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
