services:
  localstack:
    image: localstack/localstack@sha256:07dad44ca72229d6a55f16befcf3b19c0a3b5a20e608ed7ce354048547c05fa0
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
