services:
  localstack:
    image: localstack/localstack@sha256:b5830fd9617fdfba9569209436c38ce7076214016b5bff1a8f86ad8beb26c61a
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
