services:
  localstack:
    image: localstack/localstack@sha256:3a0b8a9349930996d680a863d2910e20c4f94d4044cbe583aeae5940bacb9201
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
