services:
  localstack:
    image: localstack/localstack@sha256:c59bcfbcf949f1b9ed01b8a48850e35a0458874e809ce882c8778ca0b4466df2
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
