services:
  localstack:
    image: localstack/localstack@sha256:d423c7a48f3bacbd6123b25424c888c0ac0333b3116c424d24d90cc7fac59884
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
