services:
  localstack:
    image: localstack/localstack@sha256:6d2b71f9966046cb803351d6e756d1037f523cb61c5eebcf7b12f055ab06d1e5
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
