services:
  localstack:
    image: localstack/localstack@sha256:5548ad55a7f588ee233f1590f39c7a617668c3e4a47ce5e6382154bce3106cb7
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
