services:
  localstack:
    image: localstack/localstack@sha256:6d578ccec9fe4c1e4f1e96af66931eb043a5ce769d12aa6cc91e3f2f2684632b
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
