services:
  localstack:
    image: localstack/localstack@sha256:db808f0304bcebe0257bff1920ffa2605edbf6fc504b44680789a587ebeb25b5
    profiles:
      - infra
    ports:
      - 4566:4566
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
