// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartTestRunRequest {
    #[prost(string, tag="1")]
    pub module_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub hot_reload_endpoint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartTestRunResponse {
    #[prost(string, tag="1")]
    pub deployment_key: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
