// Code generated by FTL. DO NOT EDIT.
package db

import (
	"context"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
	"github.com/block/ftl/go-runtime/server"
	stdtime "time"
)

//ftl:database postgres testdb
type TestdbConfig struct{}

type TestdbHandle = ftl.DatabaseHandle[TestdbConfig]

type FindByDataAndIdsQuery struct {
	TextFields []string
	_2s        []int
}
type RequestRow struct {
	Id        int
	Data      ftl.Option[string]
	CreatedAt stdtime.Time
}

type CreateRequestClient func(context.Context, ftl.Option[string]) error

type FindByDataAndIdsClient func(context.Context, FindByDataAndIdsQuery) ([]RequestRow, error)

type FindMultipleClient func(context.Context, []string) ([]RequestRow, error)

type GetRequestDataClient func(context.Context) ([]ftl.Option[string], error)

func init() {
	reflection.Register(
		reflection.Database[TestdbConfig]("testdb", server.InitPostgres),
	)
}
