// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: xyz/block/ftl/hotreload/v1/hotreload.proto

package hotreloadpb

import (
	v11 "github.com/block/ftl/backend/protos/xyz/block/ftl/language/v1"
	v12 "github.com/block/ftl/backend/protos/xyz/block/ftl/v1"
	v1 "github.com/block/ftl/common/protos/xyz/block/ftl/schema/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ForceNewRunner bool                   `protobuf:"varint,1,opt,name=force_new_runner,json=forceNewRunner,proto3" json:"force_new_runner,omitempty"`
	// If the schema has changed on the plugin side, this will be true
	SchemaChanged bool `protobuf:"varint,2,opt,name=schema_changed,json=schemaChanged,proto3" json:"schema_changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{0}
}

func (x *ReloadRequest) GetForceNewRunner() bool {
	if x != nil {
		return x.ForceNewRunner
	}
	return false
}

func (x *ReloadRequest) GetSchemaChanged() bool {
	if x != nil {
		return x.SchemaChanged
	}
	return false
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *SchemaState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Failed        bool                   `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{1}
}

func (x *ReloadResponse) GetState() *SchemaState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ReloadResponse) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{2}
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *SchemaState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{3}
}

func (x *WatchResponse) GetState() *SchemaState {
	if x != nil {
		return x.State
	}
	return nil
}

type RunnerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Deployment    string                 `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	SchemaVersion int64                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RunnerVersion int64                  `protobuf:"varint,4,opt,name=runner_version,json=runnerVersion,proto3" json:"runner_version,omitempty"`
	Databases     []*Database            `protobuf:"bytes,5,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerInfoRequest) Reset() {
	*x = RunnerInfoRequest{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerInfoRequest) ProtoMessage() {}

func (x *RunnerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerInfoRequest.ProtoReflect.Descriptor instead.
func (*RunnerInfoRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{4}
}

func (x *RunnerInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RunnerInfoRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *RunnerInfoRequest) GetSchemaVersion() int64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RunnerInfoRequest) GetRunnerVersion() int64 {
	if x != nil {
		return x.RunnerVersion
	}
	return 0
}

func (x *RunnerInfoRequest) GetDatabases() []*Database {
	if x != nil {
		return x.Databases
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{5}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RunnerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outdated      bool                   `protobuf:"varint,1,opt,name=outdated,proto3" json:"outdated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerInfoResponse) Reset() {
	*x = RunnerInfoResponse{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerInfoResponse) ProtoMessage() {}

func (x *RunnerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerInfoResponse.ProtoReflect.Descriptor instead.
func (*RunnerInfoResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{6}
}

func (x *RunnerInfoResponse) GetOutdated() bool {
	if x != nil {
		return x.Outdated
	}
	return false
}

type ReloadNotRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadNotRequired) Reset() {
	*x = ReloadNotRequired{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadNotRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadNotRequired) ProtoMessage() {}

func (x *ReloadNotRequired) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadNotRequired.ProtoReflect.Descriptor instead.
func (*ReloadNotRequired) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{7}
}

type ReloadSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *SchemaState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadSuccess) Reset() {
	*x = ReloadSuccess{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSuccess) ProtoMessage() {}

func (x *ReloadSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSuccess.ProtoReflect.Descriptor instead.
func (*ReloadSuccess) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{8}
}

func (x *ReloadSuccess) GetState() *SchemaState {
	if x != nil {
		return x.State
	}
	return nil
}

type ReloadFailed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module schema for the built module
	State         *SchemaState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadFailed) Reset() {
	*x = ReloadFailed{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadFailed) ProtoMessage() {}

func (x *ReloadFailed) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadFailed.ProtoReflect.Descriptor instead.
func (*ReloadFailed) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{9}
}

func (x *ReloadFailed) GetState() *SchemaState {
	if x != nil {
		return x.State
	}
	return nil
}

type SchemaState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Module            *v1.Module             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Errors            *v11.ErrorList         `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	NewRunnerRequired bool                   `protobuf:"varint,3,opt,name=new_runner_required,json=newRunnerRequired,proto3" json:"new_runner_required,omitempty"`
	Version           int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchemaState) Reset() {
	*x = SchemaState{}
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaState) ProtoMessage() {}

func (x *SchemaState) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaState.ProtoReflect.Descriptor instead.
func (*SchemaState) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP(), []int{10}
}

func (x *SchemaState) GetModule() *v1.Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *SchemaState) GetErrors() *v11.ErrorList {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SchemaState) GetNewRunnerRequired() bool {
	if x != nil {
		return x.NewRunnerRequired
	}
	return false
}

func (x *SchemaState) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_xyz_block_ftl_hotreload_v1_hotreload_proto protoreflect.FileDescriptor

const file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDesc = "" +
	"\n" +
	"*xyz/block/ftl/hotreload/v1/hotreload.proto\x12\x1axyz.block.ftl.hotreload.v1\x1a'xyz/block/ftl/language/v1/service.proto\x1a$xyz/block/ftl/schema/v1/schema.proto\x1a\x1axyz/block/ftl/v1/ftl.proto\"`\n" +
	"\rReloadRequest\x12(\n" +
	"\x10force_new_runner\x18\x01 \x01(\bR\x0eforceNewRunner\x12%\n" +
	"\x0eschema_changed\x18\x02 \x01(\bR\rschemaChanged\"g\n" +
	"\x0eReloadResponse\x12=\n" +
	"\x05state\x18\x01 \x01(\v2'.xyz.block.ftl.hotreload.v1.SchemaStateR\x05state\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\bR\x06failed\"\x0e\n" +
	"\fWatchRequest\"N\n" +
	"\rWatchResponse\x12=\n" +
	"\x05state\x18\x01 \x01(\v2'.xyz.block.ftl.hotreload.v1.SchemaStateR\x05state\"\xdf\x01\n" +
	"\x11RunnerInfoRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x03R\rschemaVersion\x12%\n" +
	"\x0erunner_version\x18\x04 \x01(\x03R\rrunnerVersion\x12B\n" +
	"\tdatabases\x18\x05 \x03(\v2$.xyz.block.ftl.hotreload.v1.DatabaseR\tdatabases\"8\n" +
	"\bDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"0\n" +
	"\x12RunnerInfoResponse\x12\x1a\n" +
	"\boutdated\x18\x01 \x01(\bR\boutdated\"\x13\n" +
	"\x11ReloadNotRequired\"N\n" +
	"\rReloadSuccess\x12=\n" +
	"\x05state\x18\x01 \x01(\v2'.xyz.block.ftl.hotreload.v1.SchemaStateR\x05state\"M\n" +
	"\fReloadFailed\x12=\n" +
	"\x05state\x18\x01 \x01(\v2'.xyz.block.ftl.hotreload.v1.SchemaStateR\x05state\"\xce\x01\n" +
	"\vSchemaState\x127\n" +
	"\x06module\x18\x01 \x01(\v2\x1f.xyz.block.ftl.schema.v1.ModuleR\x06module\x12<\n" +
	"\x06errors\x18\x02 \x01(\v2$.xyz.block.ftl.language.v1.ErrorListR\x06errors\x12.\n" +
	"\x13new_runner_required\x18\x03 \x01(\bR\x11newRunnerRequired\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion2\x8a\x03\n" +
	"\x10HotReloadService\x12J\n" +
	"\x04Ping\x12\x1d.xyz.block.ftl.v1.PingRequest\x1a\x1e.xyz.block.ftl.v1.PingResponse\"\x03\x90\x02\x01\x12_\n" +
	"\x06Reload\x12).xyz.block.ftl.hotreload.v1.ReloadRequest\x1a*.xyz.block.ftl.hotreload.v1.ReloadResponse\x12\\\n" +
	"\x05Watch\x12(.xyz.block.ftl.hotreload.v1.WatchRequest\x1a).xyz.block.ftl.hotreload.v1.WatchResponse\x12k\n" +
	"\n" +
	"RunnerInfo\x12-.xyz.block.ftl.hotreload.v1.RunnerInfoRequest\x1a..xyz.block.ftl.hotreload.v1.RunnerInfoResponseBNP\x01ZJgithub.com/block/ftl/backend/protos/xyz/block/ftl/hotreload/v1;hotreloadpbb\x06proto3"

var (
	file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescOnce sync.Once
	file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescData []byte
)

func file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescGZIP() []byte {
	file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescOnce.Do(func() {
		file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDesc), len(file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDesc)))
	})
	return file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDescData
}

var file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_xyz_block_ftl_hotreload_v1_hotreload_proto_goTypes = []any{
	(*ReloadRequest)(nil),      // 0: xyz.block.ftl.hotreload.v1.ReloadRequest
	(*ReloadResponse)(nil),     // 1: xyz.block.ftl.hotreload.v1.ReloadResponse
	(*WatchRequest)(nil),       // 2: xyz.block.ftl.hotreload.v1.WatchRequest
	(*WatchResponse)(nil),      // 3: xyz.block.ftl.hotreload.v1.WatchResponse
	(*RunnerInfoRequest)(nil),  // 4: xyz.block.ftl.hotreload.v1.RunnerInfoRequest
	(*Database)(nil),           // 5: xyz.block.ftl.hotreload.v1.Database
	(*RunnerInfoResponse)(nil), // 6: xyz.block.ftl.hotreload.v1.RunnerInfoResponse
	(*ReloadNotRequired)(nil),  // 7: xyz.block.ftl.hotreload.v1.ReloadNotRequired
	(*ReloadSuccess)(nil),      // 8: xyz.block.ftl.hotreload.v1.ReloadSuccess
	(*ReloadFailed)(nil),       // 9: xyz.block.ftl.hotreload.v1.ReloadFailed
	(*SchemaState)(nil),        // 10: xyz.block.ftl.hotreload.v1.SchemaState
	(*v1.Module)(nil),          // 11: xyz.block.ftl.schema.v1.Module
	(*v11.ErrorList)(nil),      // 12: xyz.block.ftl.language.v1.ErrorList
	(*v12.PingRequest)(nil),    // 13: xyz.block.ftl.v1.PingRequest
	(*v12.PingResponse)(nil),   // 14: xyz.block.ftl.v1.PingResponse
}
var file_xyz_block_ftl_hotreload_v1_hotreload_proto_depIdxs = []int32{
	10, // 0: xyz.block.ftl.hotreload.v1.ReloadResponse.state:type_name -> xyz.block.ftl.hotreload.v1.SchemaState
	10, // 1: xyz.block.ftl.hotreload.v1.WatchResponse.state:type_name -> xyz.block.ftl.hotreload.v1.SchemaState
	5,  // 2: xyz.block.ftl.hotreload.v1.RunnerInfoRequest.databases:type_name -> xyz.block.ftl.hotreload.v1.Database
	10, // 3: xyz.block.ftl.hotreload.v1.ReloadSuccess.state:type_name -> xyz.block.ftl.hotreload.v1.SchemaState
	10, // 4: xyz.block.ftl.hotreload.v1.ReloadFailed.state:type_name -> xyz.block.ftl.hotreload.v1.SchemaState
	11, // 5: xyz.block.ftl.hotreload.v1.SchemaState.module:type_name -> xyz.block.ftl.schema.v1.Module
	12, // 6: xyz.block.ftl.hotreload.v1.SchemaState.errors:type_name -> xyz.block.ftl.language.v1.ErrorList
	13, // 7: xyz.block.ftl.hotreload.v1.HotReloadService.Ping:input_type -> xyz.block.ftl.v1.PingRequest
	0,  // 8: xyz.block.ftl.hotreload.v1.HotReloadService.Reload:input_type -> xyz.block.ftl.hotreload.v1.ReloadRequest
	2,  // 9: xyz.block.ftl.hotreload.v1.HotReloadService.Watch:input_type -> xyz.block.ftl.hotreload.v1.WatchRequest
	4,  // 10: xyz.block.ftl.hotreload.v1.HotReloadService.RunnerInfo:input_type -> xyz.block.ftl.hotreload.v1.RunnerInfoRequest
	14, // 11: xyz.block.ftl.hotreload.v1.HotReloadService.Ping:output_type -> xyz.block.ftl.v1.PingResponse
	1,  // 12: xyz.block.ftl.hotreload.v1.HotReloadService.Reload:output_type -> xyz.block.ftl.hotreload.v1.ReloadResponse
	3,  // 13: xyz.block.ftl.hotreload.v1.HotReloadService.Watch:output_type -> xyz.block.ftl.hotreload.v1.WatchResponse
	6,  // 14: xyz.block.ftl.hotreload.v1.HotReloadService.RunnerInfo:output_type -> xyz.block.ftl.hotreload.v1.RunnerInfoResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_xyz_block_ftl_hotreload_v1_hotreload_proto_init() }
func file_xyz_block_ftl_hotreload_v1_hotreload_proto_init() {
	if File_xyz_block_ftl_hotreload_v1_hotreload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDesc), len(file_xyz_block_ftl_hotreload_v1_hotreload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_block_ftl_hotreload_v1_hotreload_proto_goTypes,
		DependencyIndexes: file_xyz_block_ftl_hotreload_v1_hotreload_proto_depIdxs,
		MessageInfos:      file_xyz_block_ftl_hotreload_v1_hotreload_proto_msgTypes,
	}.Build()
	File_xyz_block_ftl_hotreload_v1_hotreload_proto = out.File
	file_xyz_block_ftl_hotreload_v1_hotreload_proto_goTypes = nil
	file_xyz_block_ftl_hotreload_v1_hotreload_proto_depIdxs = nil
}
