fullnameOverride: "ftl"

image:
  tag: "latest"
  pullPolicy: Always
  base: "ftl:5000"

ingress:
  enabled: true
  k8sIngress: true
  image:
    repository: "ftl:5000/ftl-http-ingress"
  ingressAnnotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik

schema:
  service:
    ports:
      - name: "http-8892"
        port: 8892

runner:
  podAnnotations:
    sidecar.istio.io/logLevel: "debug"

istio:
  enabled: true

registry:
    repository: "ftl-registry:5000/ftl-artefacts"
    allowInsecure: "true"
    create: true

