
ftl-system:
  provisioner:
    userNamespace: "demo"
  runner:
    podAnnotations:
      sidecar.istio.io/logLevel: "debug"
  image:
    tag: "latest"
    pullPolicy: Always
    base: "ftl:5000"

ftl-services:
  image:
    tag: "latest"
    pullPolicy: Always
    base: "ftl:5000"

