fullnameOverride: "ftl"

ingress:
  enabled: true
  ingressAnnotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik

istio:
  enabled: true

registry:
  repository: "ftl-registry:5000/ftl-artefacts"
  allowInsecure: "true"
  create: true

