name: Build Cache
description: Cache builds
inputs:
  enable-pnpm:
    description: Enable pnpm cache
    required: false
    default: "false"
  enable-maven:
    description: Enable maven cache
    required: false
    default: "false"
runs:
  using: "composite"
  # Make sure to keep these cache entries in sync with those in writecache.yml
  steps:
    - id: reset-timestamps
      shell: bash
      run: git ls-files -z | xargs -0 touch -r go.mod
    - id: find-go-build-cache
      shell: bash
      run: echo "cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
    - id: bin-hash
      shell: bash
      run: |
        hash="$(find ./${{ inputs.working-directory }}/bin ! -type d | sort | xargs openssl sha256 | openssl sha256 -r | cut -d' ' -f1)"
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
    - name: Restore Hermit Cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ${{ runner.os == 'macOS' && '~/Library/Caches/hermit/pkg' || '~/.cache/hermit/pkg' }}
        key: ${{ runner.os }}-${{ runner.arch }}-hermit-cache-${{ steps.bin-hash.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-hermit-cache-${{ steps.bin-hash.outputs.hash }}
          ${{ runner.os }}-${{ runner.arch }}-hermit-cache-
    - name: Restore Go Modules Cache
      id: cache-go-modules
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/go/pkg/mod
          ${{ steps.find-go-build-cache.outputs.cache }}
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          ${{ runner.os }}-go-
    - name: Restore Maven Modules Cache
      if: ${{ inputs.enable-maven == 'true' }}
      id: cache-maven
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-maven-
    - name: Restore pnpm Cache
      id: cache-pnpm
      if: ${{ inputs.enable-pnpm == 'true' }}
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/.pnpm-store
          node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          ${{ runner.os }}-${{ runner.arch }}-pnpm-
