// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file xyz/block/ftl/buildengine/v1/buildengine.proto (package xyz.block.ftl.buildengine.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingRequest, PingResponse } from "../../v1/ftl_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { StreamEngineEventsRequest, StreamEngineEventsResponse } from "./buildengine_pb.js";

/**
 * @generated from service xyz.block.ftl.buildengine.v1.BuildEngineService
 */
export const BuildEngineService = {
  typeName: "xyz.block.ftl.buildengine.v1.BuildEngineService",
  methods: {
    /**
     * Ping service for readiness.
     *
     * @generated from rpc xyz.block.ftl.buildengine.v1.BuildEngineService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc xyz.block.ftl.buildengine.v1.BuildEngineService.StreamEngineEvents
     */
    streamEngineEvents: {
      name: "StreamEngineEvents",
      I: StreamEngineEventsRequest,
      O: StreamEngineEventsResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

