#!/bin/bash
set -euo pipefail

# We only want to build this for the current platform
# This may get invoked as part of a build for a different platform
unset GOARCH
unset GOOS
export CGO_ENABLED=0

ftldir="$(dirname "$(readlink -f "$0")")/.."

if [ ! "${HERMIT_ENV}" -ef "${ftldir}" ]; then
  # shellcheck disable=SC1091
  . "${ftldir}/bin/activate-hermit"
fi

name="$(basename "$0")"

if [ "${USE_RELEASE_BINARIES:-0}" = "1" ]; then
  exec "${ftldir}/build/release/$name" "$@"
fi

dest="${ftldir}/build/devel"
src="./cmd/${name}"
mkdir -p "$dest"

"${ftldir}/bin/go" build -C "${ftldir}/${src}" -ldflags="-s -w -buildid=" -o "$dest/${name}" . && exec "$dest/${name}" "$@"
