#!/bin/bash
set -euo pipefail

# We only want to build this for the current platform
# This may get invoked as part of a build for a different platform
unset GOARCH
unset GOOS

FTL_DIR="$(dirname "$(readlink -f "$0")")/.."
export FTL_DIR

if [ ! "${HERMIT_ENV}" -ef "${FTL_DIR}" ]; then
  # shellcheck disable=SC1091
  . "${FTL_DIR}/bin/activate-hermit"
fi

name="$(basename "$0")"
dest="${FTL_DIR}/build/devel"
src="./cmd/${name}"
mkdir -p "$dest"
"${FTL_DIR}/bin/go" build -C "${FTL_DIR}/${src}" -ldflags="-s -w -buildid=" -o "$dest/${name}" . && exec "$dest/${name}" "$@"
