#!/bin/bash
set -euo pipefail
export CGO_ENABLED=0
exe="$0"
ftldir="$(dirname "$exe")/.."
language="${exe/*-/}"
dirlang="${language}"
name="ftl-language-${language}"

if [ "${USE_RELEASE_BINARIES:-0}" = "1" ]; then
  exec "${ftldir}/build/release/$name" "$@"
fi

if [ "${dirlang}" = "java" ] || [ "${dirlang}" = "kotlin" ]; then
    dirlang="jvm"
fi
if [ -n "${CI-}" ]; then
  dest="${ftldir}/build/release"
else
  dest="${ftldir}/build/devel"
  mkdir -p "$dest"
  (cd "${ftldir}/${dirlang}-runtime/cmd/ftl-language-${language}" && "${ftldir}/bin/go" build -ldflags="-s -w -buildid=" -o "$dest/${name}" ./)
fi
exec "$dest/${name}" "$@"
