services:
  otel-lgtm:
    image: ${FTL_GRAFANA_IMAGE:-grafana/otel-lgtm@sha256:b2c618db1c04e0587dfd326080bb271cd0b0d7ced1dae4680ff2c2046e9e3e1c}
    ports:
      - 3000:3000 # Portal Endpoint
      - 9090:9090 # Prometheus
      - ${OTEL_GRPC_PORT:-4317}:4317 # OTLP GRPC Collector
      - ${OTEL_HTTP_PORT:-4318}:4318 # OTLP HTTP Collector
    environment:
      - ENABLE_LOGS_ALL=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

volumes:
  grafana-storage: {}
