services:
  db:
    image: ${FTL_DATABASE_IMAGE:-postgres:15.12@sha256:fe45ed1a824b81c0c9c605890963b67501758ca8c946db89089c85ce0f88e974}
    command: postgres
    user: postgres
    # For local debugging
    # -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c log_statement=all
    # volumes:
    #   - ./logs:/logs
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - ${FTL_DB_PORT:-15432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
