services:
  mysql:
    image: mysql:8.4.3@sha256:106d5197fd8e4892980469ad42eb20f7a336bd81509aae4ee175d852f5cc4565
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: ftl
    ports:
      - "${FTL_MYSQL_PORT:-13306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
