services:
  mysql:
    image: mysql:9.1.0@sha256:0255b469f0135a0236d672d60e3154ae2f4538b146744966d96440318cc822c6
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: ftl
    ports:
      - "${FTL_MYSQL_PORT:-13306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
