// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: xyz/block/ftl/v1/schemaservice.proto

package ftlv1

import (
	v1 "github.com/block/ftl/common/protos/xyz/block/ftl/schema/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{0}
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *v1.Schema             `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Changesets    []*v1.Changeset        `protobuf:"bytes,2,rep,name=changesets,proto3" json:"changesets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetSchemaResponse) GetSchema() *v1.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GetSchemaResponse) GetChangesets() []*v1.Changeset {
	if x != nil {
		return x.Changesets
	}
	return nil
}

type PullSchemaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullSchemaRequest) Reset() {
	*x = PullSchemaRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullSchemaRequest) ProtoMessage() {}

func (x *PullSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullSchemaRequest.ProtoReflect.Descriptor instead.
func (*PullSchemaRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{2}
}

func (x *PullSchemaRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type PullSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Notification       `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullSchemaResponse) Reset() {
	*x = PullSchemaResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullSchemaResponse) ProtoMessage() {}

func (x *PullSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullSchemaResponse.ProtoReflect.Descriptor instead.
func (*PullSchemaResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{3}
}

func (x *PullSchemaResponse) GetEvent() *v1.Notification {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateDeploymentRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changeset     *string                `protobuf:"bytes,1,opt,name=changeset,proto3,oneof" json:"changeset,omitempty"`
	Update        *v1.RuntimeElement     `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeploymentRuntimeRequest) Reset() {
	*x = UpdateDeploymentRuntimeRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeploymentRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeploymentRuntimeRequest) ProtoMessage() {}

func (x *UpdateDeploymentRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeploymentRuntimeRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeploymentRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDeploymentRuntimeRequest) GetChangeset() string {
	if x != nil && x.Changeset != nil {
		return *x.Changeset
	}
	return ""
}

func (x *UpdateDeploymentRuntimeRequest) GetUpdate() *v1.RuntimeElement {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateDeploymentRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeploymentRuntimeResponse) Reset() {
	*x = UpdateDeploymentRuntimeResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeploymentRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeploymentRuntimeResponse) ProtoMessage() {}

func (x *UpdateDeploymentRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeploymentRuntimeResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeploymentRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{5}
}

type GetDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentsRequest) Reset() {
	*x = GetDeploymentsRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentsRequest) ProtoMessage() {}

func (x *GetDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{6}
}

type GetDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        []*DeployedSchema      `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentsResponse) Reset() {
	*x = GetDeploymentsResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentsResponse) ProtoMessage() {}

func (x *GetDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeploymentsResponse) GetSchema() []*DeployedSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RealmChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The modules to add or update.
	Modules []*v1.Module `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	// The deployments to remove.
	ToRemove      []string `protobuf:"bytes,3,rep,name=to_remove,json=toRemove,proto3" json:"to_remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealmChange) Reset() {
	*x = RealmChange{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealmChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealmChange) ProtoMessage() {}

func (x *RealmChange) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealmChange.ProtoReflect.Descriptor instead.
func (*RealmChange) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{8}
}

func (x *RealmChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RealmChange) GetModules() []*v1.Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *RealmChange) GetToRemove() []string {
	if x != nil {
		return x.ToRemove
	}
	return nil
}

type CreateChangesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmChanges  []*RealmChange         `protobuf:"bytes,1,rep,name=realm_changes,json=realmChanges,proto3" json:"realm_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChangesetRequest) Reset() {
	*x = CreateChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChangesetRequest) ProtoMessage() {}

func (x *CreateChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChangesetRequest.ProtoReflect.Descriptor instead.
func (*CreateChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{9}
}

func (x *CreateChangesetRequest) GetRealmChanges() []*RealmChange {
	if x != nil {
		return x.RealmChanges
	}
	return nil
}

type CreateChangesetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key of the newly created changeset.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChangesetResponse) Reset() {
	*x = CreateChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChangesetResponse) ProtoMessage() {}

func (x *CreateChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChangesetResponse.ProtoReflect.Descriptor instead.
func (*CreateChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{10}
}

func (x *CreateChangesetResponse) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

type DeployedSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentKey string                 `protobuf:"bytes,1,opt,name=deployment_key,json=deploymentKey,proto3" json:"deployment_key,omitempty"`
	Schema        *v1.Module             `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployedSchema) Reset() {
	*x = DeployedSchema{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployedSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployedSchema) ProtoMessage() {}

func (x *DeployedSchema) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployedSchema.ProtoReflect.Descriptor instead.
func (*DeployedSchema) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{11}
}

func (x *DeployedSchema) GetDeploymentKey() string {
	if x != nil {
		return x.DeploymentKey
	}
	return ""
}

func (x *DeployedSchema) GetSchema() *v1.Module {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *DeployedSchema) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type PrepareChangesetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key to prepare.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareChangesetRequest) Reset() {
	*x = PrepareChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareChangesetRequest) ProtoMessage() {}

func (x *PrepareChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareChangesetRequest.ProtoReflect.Descriptor instead.
func (*PrepareChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{12}
}

func (x *PrepareChangesetRequest) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

type PrepareChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareChangesetResponse) Reset() {
	*x = PrepareChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareChangesetResponse) ProtoMessage() {}

func (x *PrepareChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareChangesetResponse.ProtoReflect.Descriptor instead.
func (*PrepareChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{13}
}

type CommitChangesetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key to commit.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitChangesetRequest) Reset() {
	*x = CommitChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitChangesetRequest) ProtoMessage() {}

func (x *CommitChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitChangesetRequest.ProtoReflect.Descriptor instead.
func (*CommitChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{14}
}

func (x *CommitChangesetRequest) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

type CommitChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changeset     *v1.Changeset          `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitChangesetResponse) Reset() {
	*x = CommitChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitChangesetResponse) ProtoMessage() {}

func (x *CommitChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitChangesetResponse.ProtoReflect.Descriptor instead.
func (*CommitChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{15}
}

func (x *CommitChangesetResponse) GetChangeset() *v1.Changeset {
	if x != nil {
		return x.Changeset
	}
	return nil
}

type DrainChangesetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key to commit.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainChangesetRequest) Reset() {
	*x = DrainChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainChangesetRequest) ProtoMessage() {}

func (x *DrainChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainChangesetRequest.ProtoReflect.Descriptor instead.
func (*DrainChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{16}
}

func (x *DrainChangesetRequest) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

type DrainChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainChangesetResponse) Reset() {
	*x = DrainChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainChangesetResponse) ProtoMessage() {}

func (x *DrainChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainChangesetResponse.ProtoReflect.Descriptor instead.
func (*DrainChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{17}
}

type FinalizeChangesetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key to commit.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeChangesetRequest) Reset() {
	*x = FinalizeChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeChangesetRequest) ProtoMessage() {}

func (x *FinalizeChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeChangesetRequest.ProtoReflect.Descriptor instead.
func (*FinalizeChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{18}
}

func (x *FinalizeChangesetRequest) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

type FinalizeChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeChangesetResponse) Reset() {
	*x = FinalizeChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeChangesetResponse) ProtoMessage() {}

func (x *FinalizeChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeChangesetResponse.ProtoReflect.Descriptor instead.
func (*FinalizeChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{19}
}

type FailChangesetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key to fail.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailChangesetRequest) Reset() {
	*x = FailChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailChangesetRequest) ProtoMessage() {}

func (x *FailChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailChangesetRequest.ProtoReflect.Descriptor instead.
func (*FailChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{20}
}

func (x *FailChangesetRequest) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

type FailChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailChangesetResponse) Reset() {
	*x = FailChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailChangesetResponse) ProtoMessage() {}

func (x *FailChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailChangesetResponse.ProtoReflect.Descriptor instead.
func (*FailChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{21}
}

type RollbackChangesetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changeset key to fail.
	Changeset     string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackChangesetRequest) Reset() {
	*x = RollbackChangesetRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackChangesetRequest) ProtoMessage() {}

func (x *RollbackChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackChangesetRequest.ProtoReflect.Descriptor instead.
func (*RollbackChangesetRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{22}
}

func (x *RollbackChangesetRequest) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

func (x *RollbackChangesetRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RollbackChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changeset     *v1.Changeset          `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackChangesetResponse) Reset() {
	*x = RollbackChangesetResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackChangesetResponse) ProtoMessage() {}

func (x *RollbackChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackChangesetResponse.ProtoReflect.Descriptor instead.
func (*RollbackChangesetResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{23}
}

func (x *RollbackChangesetResponse) GetChangeset() *v1.Changeset {
	if x != nil {
		return x.Changeset
	}
	return nil
}

type GetDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentKey string                 `protobuf:"bytes,1,opt,name=deployment_key,json=deploymentKey,proto3" json:"deployment_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentRequest) Reset() {
	*x = GetDeploymentRequest{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentRequest) ProtoMessage() {}

func (x *GetDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{24}
}

func (x *GetDeploymentRequest) GetDeploymentKey() string {
	if x != nil {
		return x.DeploymentKey
	}
	return ""
}

type GetDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *v1.Module             `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentResponse) Reset() {
	*x = GetDeploymentResponse{}
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentResponse) ProtoMessage() {}

func (x *GetDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP(), []int{25}
}

func (x *GetDeploymentResponse) GetSchema() *v1.Module {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_xyz_block_ftl_v1_schemaservice_proto protoreflect.FileDescriptor

const file_xyz_block_ftl_v1_schemaservice_proto_rawDesc = "" +
	"\n" +
	"$xyz/block/ftl/v1/schemaservice.proto\x12\x10xyz.block.ftl.v1\x1a$xyz/block/ftl/schema/v1/schema.proto\x1a\x1axyz/block/ftl/v1/ftl.proto\"\x12\n" +
	"\x10GetSchemaRequest\"\x90\x01\n" +
	"\x11GetSchemaResponse\x127\n" +
	"\x06schema\x18\x01 \x01(\v2\x1f.xyz.block.ftl.schema.v1.SchemaR\x06schema\x12B\n" +
	"\n" +
	"changesets\x18\x02 \x03(\v2\".xyz.block.ftl.schema.v1.ChangesetR\n" +
	"changesets\"<\n" +
	"\x11PullSchemaRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"Q\n" +
	"\x12PullSchemaResponse\x12;\n" +
	"\x05event\x18\x01 \x01(\v2%.xyz.block.ftl.schema.v1.NotificationR\x05event\"\x92\x01\n" +
	"\x1eUpdateDeploymentRuntimeRequest\x12!\n" +
	"\tchangeset\x18\x01 \x01(\tH\x00R\tchangeset\x88\x01\x01\x12?\n" +
	"\x06update\x18\x02 \x01(\v2'.xyz.block.ftl.schema.v1.RuntimeElementR\x06updateB\f\n" +
	"\n" +
	"_changeset\"!\n" +
	"\x1fUpdateDeploymentRuntimeResponse\"\x17\n" +
	"\x15GetDeploymentsRequest\"R\n" +
	"\x16GetDeploymentsResponse\x128\n" +
	"\x06schema\x18\x01 \x03(\v2 .xyz.block.ftl.v1.DeployedSchemaR\x06schema\"y\n" +
	"\vRealmChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\amodules\x18\x02 \x03(\v2\x1f.xyz.block.ftl.schema.v1.ModuleR\amodules\x12\x1b\n" +
	"\tto_remove\x18\x03 \x03(\tR\btoRemove\"\\\n" +
	"\x16CreateChangesetRequest\x12B\n" +
	"\rrealm_changes\x18\x01 \x03(\v2\x1d.xyz.block.ftl.v1.RealmChangeR\frealmChanges\"7\n" +
	"\x17CreateChangesetResponse\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\"\x8d\x01\n" +
	"\x0eDeployedSchema\x12%\n" +
	"\x0edeployment_key\x18\x01 \x01(\tR\rdeploymentKey\x127\n" +
	"\x06schema\x18\x02 \x01(\v2\x1f.xyz.block.ftl.schema.v1.ModuleR\x06schema\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"7\n" +
	"\x17PrepareChangesetRequest\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\"\x1a\n" +
	"\x18PrepareChangesetResponse\"6\n" +
	"\x16CommitChangesetRequest\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\"[\n" +
	"\x17CommitChangesetResponse\x12@\n" +
	"\tchangeset\x18\x01 \x01(\v2\".xyz.block.ftl.schema.v1.ChangesetR\tchangeset\"5\n" +
	"\x15DrainChangesetRequest\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\"\x18\n" +
	"\x16DrainChangesetResponse\"8\n" +
	"\x18FinalizeChangesetRequest\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\"\x1b\n" +
	"\x19FinalizeChangesetResponse\"4\n" +
	"\x14FailChangesetRequest\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\"\x17\n" +
	"\x15FailChangesetResponse\"N\n" +
	"\x18RollbackChangesetRequest\x12\x1c\n" +
	"\tchangeset\x18\x01 \x01(\tR\tchangeset\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"]\n" +
	"\x19RollbackChangesetResponse\x12@\n" +
	"\tchangeset\x18\x01 \x01(\v2\".xyz.block.ftl.schema.v1.ChangesetR\tchangeset\"=\n" +
	"\x14GetDeploymentRequest\x12%\n" +
	"\x0edeployment_key\x18\x01 \x01(\tR\rdeploymentKey\"P\n" +
	"\x15GetDeploymentResponse\x127\n" +
	"\x06schema\x18\x01 \x01(\v2\x1f.xyz.block.ftl.schema.v1.ModuleR\x06schema2\xbb\n" +
	"\n" +
	"\rSchemaService\x12J\n" +
	"\x04Ping\x12\x1d.xyz.block.ftl.v1.PingRequest\x1a\x1e.xyz.block.ftl.v1.PingResponse\"\x03\x90\x02\x01\x12Y\n" +
	"\tGetSchema\x12\".xyz.block.ftl.v1.GetSchemaRequest\x1a#.xyz.block.ftl.v1.GetSchemaResponse\"\x03\x90\x02\x01\x12^\n" +
	"\n" +
	"PullSchema\x12#.xyz.block.ftl.v1.PullSchemaRequest\x1a$.xyz.block.ftl.v1.PullSchemaResponse\"\x03\x90\x02\x010\x01\x12~\n" +
	"\x17UpdateDeploymentRuntime\x120.xyz.block.ftl.v1.UpdateDeploymentRuntimeRequest\x1a1.xyz.block.ftl.v1.UpdateDeploymentRuntimeResponse\x12c\n" +
	"\x0eGetDeployments\x12'.xyz.block.ftl.v1.GetDeploymentsRequest\x1a(.xyz.block.ftl.v1.GetDeploymentsResponse\x12f\n" +
	"\x0fCreateChangeset\x12(.xyz.block.ftl.v1.CreateChangesetRequest\x1a).xyz.block.ftl.v1.CreateChangesetResponse\x12i\n" +
	"\x10PrepareChangeset\x12).xyz.block.ftl.v1.PrepareChangesetRequest\x1a*.xyz.block.ftl.v1.PrepareChangesetResponse\x12f\n" +
	"\x0fCommitChangeset\x12(.xyz.block.ftl.v1.CommitChangesetRequest\x1a).xyz.block.ftl.v1.CommitChangesetResponse\x12c\n" +
	"\x0eDrainChangeset\x12'.xyz.block.ftl.v1.DrainChangesetRequest\x1a(.xyz.block.ftl.v1.DrainChangesetResponse\x12l\n" +
	"\x11FinalizeChangeset\x12*.xyz.block.ftl.v1.FinalizeChangesetRequest\x1a+.xyz.block.ftl.v1.FinalizeChangesetResponse\x12l\n" +
	"\x11RollbackChangeset\x12*.xyz.block.ftl.v1.RollbackChangesetRequest\x1a+.xyz.block.ftl.v1.RollbackChangesetResponse\x12`\n" +
	"\rFailChangeset\x12&.xyz.block.ftl.v1.FailChangesetRequest\x1a'.xyz.block.ftl.v1.FailChangesetResponse\x12`\n" +
	"\rGetDeployment\x12&.xyz.block.ftl.v1.GetDeploymentRequest\x1a'.xyz.block.ftl.v1.GetDeploymentResponseB>P\x01Z:github.com/block/ftl/backend/protos/xyz/block/ftl/v1;ftlv1b\x06proto3"

var (
	file_xyz_block_ftl_v1_schemaservice_proto_rawDescOnce sync.Once
	file_xyz_block_ftl_v1_schemaservice_proto_rawDescData []byte
)

func file_xyz_block_ftl_v1_schemaservice_proto_rawDescGZIP() []byte {
	file_xyz_block_ftl_v1_schemaservice_proto_rawDescOnce.Do(func() {
		file_xyz_block_ftl_v1_schemaservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_block_ftl_v1_schemaservice_proto_rawDesc), len(file_xyz_block_ftl_v1_schemaservice_proto_rawDesc)))
	})
	return file_xyz_block_ftl_v1_schemaservice_proto_rawDescData
}

var file_xyz_block_ftl_v1_schemaservice_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_xyz_block_ftl_v1_schemaservice_proto_goTypes = []any{
	(*GetSchemaRequest)(nil),                // 0: xyz.block.ftl.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),               // 1: xyz.block.ftl.v1.GetSchemaResponse
	(*PullSchemaRequest)(nil),               // 2: xyz.block.ftl.v1.PullSchemaRequest
	(*PullSchemaResponse)(nil),              // 3: xyz.block.ftl.v1.PullSchemaResponse
	(*UpdateDeploymentRuntimeRequest)(nil),  // 4: xyz.block.ftl.v1.UpdateDeploymentRuntimeRequest
	(*UpdateDeploymentRuntimeResponse)(nil), // 5: xyz.block.ftl.v1.UpdateDeploymentRuntimeResponse
	(*GetDeploymentsRequest)(nil),           // 6: xyz.block.ftl.v1.GetDeploymentsRequest
	(*GetDeploymentsResponse)(nil),          // 7: xyz.block.ftl.v1.GetDeploymentsResponse
	(*RealmChange)(nil),                     // 8: xyz.block.ftl.v1.RealmChange
	(*CreateChangesetRequest)(nil),          // 9: xyz.block.ftl.v1.CreateChangesetRequest
	(*CreateChangesetResponse)(nil),         // 10: xyz.block.ftl.v1.CreateChangesetResponse
	(*DeployedSchema)(nil),                  // 11: xyz.block.ftl.v1.DeployedSchema
	(*PrepareChangesetRequest)(nil),         // 12: xyz.block.ftl.v1.PrepareChangesetRequest
	(*PrepareChangesetResponse)(nil),        // 13: xyz.block.ftl.v1.PrepareChangesetResponse
	(*CommitChangesetRequest)(nil),          // 14: xyz.block.ftl.v1.CommitChangesetRequest
	(*CommitChangesetResponse)(nil),         // 15: xyz.block.ftl.v1.CommitChangesetResponse
	(*DrainChangesetRequest)(nil),           // 16: xyz.block.ftl.v1.DrainChangesetRequest
	(*DrainChangesetResponse)(nil),          // 17: xyz.block.ftl.v1.DrainChangesetResponse
	(*FinalizeChangesetRequest)(nil),        // 18: xyz.block.ftl.v1.FinalizeChangesetRequest
	(*FinalizeChangesetResponse)(nil),       // 19: xyz.block.ftl.v1.FinalizeChangesetResponse
	(*FailChangesetRequest)(nil),            // 20: xyz.block.ftl.v1.FailChangesetRequest
	(*FailChangesetResponse)(nil),           // 21: xyz.block.ftl.v1.FailChangesetResponse
	(*RollbackChangesetRequest)(nil),        // 22: xyz.block.ftl.v1.RollbackChangesetRequest
	(*RollbackChangesetResponse)(nil),       // 23: xyz.block.ftl.v1.RollbackChangesetResponse
	(*GetDeploymentRequest)(nil),            // 24: xyz.block.ftl.v1.GetDeploymentRequest
	(*GetDeploymentResponse)(nil),           // 25: xyz.block.ftl.v1.GetDeploymentResponse
	(*v1.Schema)(nil),                       // 26: xyz.block.ftl.schema.v1.Schema
	(*v1.Changeset)(nil),                    // 27: xyz.block.ftl.schema.v1.Changeset
	(*v1.Notification)(nil),                 // 28: xyz.block.ftl.schema.v1.Notification
	(*v1.RuntimeElement)(nil),               // 29: xyz.block.ftl.schema.v1.RuntimeElement
	(*v1.Module)(nil),                       // 30: xyz.block.ftl.schema.v1.Module
	(*PingRequest)(nil),                     // 31: xyz.block.ftl.v1.PingRequest
	(*PingResponse)(nil),                    // 32: xyz.block.ftl.v1.PingResponse
}
var file_xyz_block_ftl_v1_schemaservice_proto_depIdxs = []int32{
	26, // 0: xyz.block.ftl.v1.GetSchemaResponse.schema:type_name -> xyz.block.ftl.schema.v1.Schema
	27, // 1: xyz.block.ftl.v1.GetSchemaResponse.changesets:type_name -> xyz.block.ftl.schema.v1.Changeset
	28, // 2: xyz.block.ftl.v1.PullSchemaResponse.event:type_name -> xyz.block.ftl.schema.v1.Notification
	29, // 3: xyz.block.ftl.v1.UpdateDeploymentRuntimeRequest.update:type_name -> xyz.block.ftl.schema.v1.RuntimeElement
	11, // 4: xyz.block.ftl.v1.GetDeploymentsResponse.schema:type_name -> xyz.block.ftl.v1.DeployedSchema
	30, // 5: xyz.block.ftl.v1.RealmChange.modules:type_name -> xyz.block.ftl.schema.v1.Module
	8,  // 6: xyz.block.ftl.v1.CreateChangesetRequest.realm_changes:type_name -> xyz.block.ftl.v1.RealmChange
	30, // 7: xyz.block.ftl.v1.DeployedSchema.schema:type_name -> xyz.block.ftl.schema.v1.Module
	27, // 8: xyz.block.ftl.v1.CommitChangesetResponse.changeset:type_name -> xyz.block.ftl.schema.v1.Changeset
	27, // 9: xyz.block.ftl.v1.RollbackChangesetResponse.changeset:type_name -> xyz.block.ftl.schema.v1.Changeset
	30, // 10: xyz.block.ftl.v1.GetDeploymentResponse.schema:type_name -> xyz.block.ftl.schema.v1.Module
	31, // 11: xyz.block.ftl.v1.SchemaService.Ping:input_type -> xyz.block.ftl.v1.PingRequest
	0,  // 12: xyz.block.ftl.v1.SchemaService.GetSchema:input_type -> xyz.block.ftl.v1.GetSchemaRequest
	2,  // 13: xyz.block.ftl.v1.SchemaService.PullSchema:input_type -> xyz.block.ftl.v1.PullSchemaRequest
	4,  // 14: xyz.block.ftl.v1.SchemaService.UpdateDeploymentRuntime:input_type -> xyz.block.ftl.v1.UpdateDeploymentRuntimeRequest
	6,  // 15: xyz.block.ftl.v1.SchemaService.GetDeployments:input_type -> xyz.block.ftl.v1.GetDeploymentsRequest
	9,  // 16: xyz.block.ftl.v1.SchemaService.CreateChangeset:input_type -> xyz.block.ftl.v1.CreateChangesetRequest
	12, // 17: xyz.block.ftl.v1.SchemaService.PrepareChangeset:input_type -> xyz.block.ftl.v1.PrepareChangesetRequest
	14, // 18: xyz.block.ftl.v1.SchemaService.CommitChangeset:input_type -> xyz.block.ftl.v1.CommitChangesetRequest
	16, // 19: xyz.block.ftl.v1.SchemaService.DrainChangeset:input_type -> xyz.block.ftl.v1.DrainChangesetRequest
	18, // 20: xyz.block.ftl.v1.SchemaService.FinalizeChangeset:input_type -> xyz.block.ftl.v1.FinalizeChangesetRequest
	22, // 21: xyz.block.ftl.v1.SchemaService.RollbackChangeset:input_type -> xyz.block.ftl.v1.RollbackChangesetRequest
	20, // 22: xyz.block.ftl.v1.SchemaService.FailChangeset:input_type -> xyz.block.ftl.v1.FailChangesetRequest
	24, // 23: xyz.block.ftl.v1.SchemaService.GetDeployment:input_type -> xyz.block.ftl.v1.GetDeploymentRequest
	32, // 24: xyz.block.ftl.v1.SchemaService.Ping:output_type -> xyz.block.ftl.v1.PingResponse
	1,  // 25: xyz.block.ftl.v1.SchemaService.GetSchema:output_type -> xyz.block.ftl.v1.GetSchemaResponse
	3,  // 26: xyz.block.ftl.v1.SchemaService.PullSchema:output_type -> xyz.block.ftl.v1.PullSchemaResponse
	5,  // 27: xyz.block.ftl.v1.SchemaService.UpdateDeploymentRuntime:output_type -> xyz.block.ftl.v1.UpdateDeploymentRuntimeResponse
	7,  // 28: xyz.block.ftl.v1.SchemaService.GetDeployments:output_type -> xyz.block.ftl.v1.GetDeploymentsResponse
	10, // 29: xyz.block.ftl.v1.SchemaService.CreateChangeset:output_type -> xyz.block.ftl.v1.CreateChangesetResponse
	13, // 30: xyz.block.ftl.v1.SchemaService.PrepareChangeset:output_type -> xyz.block.ftl.v1.PrepareChangesetResponse
	15, // 31: xyz.block.ftl.v1.SchemaService.CommitChangeset:output_type -> xyz.block.ftl.v1.CommitChangesetResponse
	17, // 32: xyz.block.ftl.v1.SchemaService.DrainChangeset:output_type -> xyz.block.ftl.v1.DrainChangesetResponse
	19, // 33: xyz.block.ftl.v1.SchemaService.FinalizeChangeset:output_type -> xyz.block.ftl.v1.FinalizeChangesetResponse
	23, // 34: xyz.block.ftl.v1.SchemaService.RollbackChangeset:output_type -> xyz.block.ftl.v1.RollbackChangesetResponse
	21, // 35: xyz.block.ftl.v1.SchemaService.FailChangeset:output_type -> xyz.block.ftl.v1.FailChangesetResponse
	25, // 36: xyz.block.ftl.v1.SchemaService.GetDeployment:output_type -> xyz.block.ftl.v1.GetDeploymentResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_xyz_block_ftl_v1_schemaservice_proto_init() }
func file_xyz_block_ftl_v1_schemaservice_proto_init() {
	if File_xyz_block_ftl_v1_schemaservice_proto != nil {
		return
	}
	file_xyz_block_ftl_v1_ftl_proto_init()
	file_xyz_block_ftl_v1_schemaservice_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_block_ftl_v1_schemaservice_proto_rawDesc), len(file_xyz_block_ftl_v1_schemaservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_block_ftl_v1_schemaservice_proto_goTypes,
		DependencyIndexes: file_xyz_block_ftl_v1_schemaservice_proto_depIdxs,
		MessageInfos:      file_xyz_block_ftl_v1_schemaservice_proto_msgTypes,
	}.Build()
	File_xyz_block_ftl_v1_schemaservice_proto = out.File
	file_xyz_block_ftl_v1_schemaservice_proto_goTypes = nil
	file_xyz_block_ftl_v1_schemaservice_proto_depIdxs = nil
}
