on:
  pull_request:
name: Conventional Commits
jobs:
  cc:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # ratchet:cashapp/activate-hermit@v1.1.4
      - name: Update PR title
        run: |
          gh pr view --json title -q .title | grep -qE '^(\w+)[:(]' && exit 0
          modified="$(gptcc "$orig")"
          diff -u <(echo "$orig") <(echo "$modified") | tail +4 || true
          gh pr edit --title "$modified"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          orig: ${{ github.event.pull_request.title }}
