on:
  workflow_dispatch:
  pull_request:
    types: [closed]
name: Manually Create New Release
jobs:
  semver-tag:
    name: Conventional Commits Auto-version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release after merge'))
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Init Hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # ratchet:cashapp/activate-hermit@v1.1.4
      - name: Auto-version
        id: autoversion
        run: scripts/autoversion
        env:
          GH_TOKEN: ${{ secrets.FTL_AUTOVERSION_TOKEN }}
