on:
  workflow_dispatch:
name: Manually Create New Release
jobs:
  semver-tag:
    name: Conventional Commits Auto-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Init Hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # ratchet:cashapp/activate-hermit@v1.1.4
      - name: Auto-version
        id: autoversion
        run: scripts/autoversion
        env:
          GH_TOKEN: ${{ secrets.FTL_AUTOVERSION_TOKEN }}
